# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

#config.vm.synced_folder "/home/user/vagrant", "/home/vagrant"
  config.vm.provision "file", source: "/home/user/tp-r504/TP5/vag1/index.html", destination: "index.html"

#Ajout du provisionnement shell
config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nginx
  SHELL

config.vm.provision "file", source: "nginx.conf", destination: "/home/vagrant/nginx.conf
"
#Sauvegrade du fichier nginx.conf par defaut
  config.vm.provision "shell", inline: "cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old"

  config.vm.provision "shell", inline: "cp nginx.conf /etc/nginx/nginx.conf"
  config.vm.provision "shell", inline: "systemctl start nginx"

# Translation de port
  config.vm.network "forwarded_port", guest: 80, host: 8080

end
