# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

#config.vm.synced_folder "/home/user/vagrant", "/home/vagrant"
  config.vm.provision "file", source: "/home/user/tp-r504/TP5/vag1/index.html", destination: "index.html"

#Ajout du provisionnement shell
config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y nginx
  SHELL

config.vm.provision "file", source: "nginx.conf", destination: "/tmp/nginx.conf"
  config.vm.provision "shell", inline: "sudo cp /tmp/nginx.conf /etc/nginx/sites-available/default"
  config.vm.provision "shell", inline: "sudo systemctl start nginx"

# Translation de port
  config.vm.network "forwarded_port", guest: 80, host: 8080

end
