name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - name: Set up Python for Demo
        uses: actions/setup-puthon@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: installation de pytest
        run: pip3 install pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name: Nom de branche
        run: "echo Nom branche : ${{ github.ref }}"
      - name: Nom du repo
        run: "echo Nom repo : ${{ github.repository }}."


